import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import Header from "../components/layout/Header";
import "./styles/globals.css";

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  weight: ['200', '400', '600'],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Voidground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} ${robotoMono.variable} antialiased overflow-x-hidden`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
